#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__) + '/lib') unless $:.include?(File.dirname(__FILE__) + '/lib')

require 'bombshell'
require 'mission_control'

Bombshell.launch(MissionControl::Shells::Main)