#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__)) unless $:.include?(File.dirname(__FILE__))

require 'bombshell'
require 'rubygems'
require 'lib/mission_control'

Bombshell.launch(MissionControl::Shell)