#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__) + '/lib') unless $:.include?(File.dirname(__FILE__) + '/lib')

require 'bombshell'
require 'iterm_automator'
require 'main'
require 'rubygems'

Bombshell.launch(Main::Shell)